### ISSUE TITLE
Close button on plotter window is broken

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#109]
When closing a plotter, you currently must press the `q` button. If you press the exit button in the window, the plotter does not properly closed. For example:

```py
import vtki
from vtki import examples

data = examples.load_uniform()

p = vtki.Plotter(notebook=False)
p.add_mesh(data)
p.show(screenshot='foo.png') # USE EXIT BUTTON NOT Q KEY
```

which produces a blank image because I guess the renderer is destroyed before the screenshot code is executed:

![foo](https://user-images.githubusercontent.com/22067021/53617969-b17ed500-3ba6-11e9-83ae-bdc9d92b2e02.png)

**Comment by akaszynski** [comment]
Fixed in b43e2af0adeb13eeeea0b12e75ec436dd03829b1.
