### ISSUE TITLE
Package on conda forge

### ISSUE THREAD

**Issue by hadim** [vtkiorg/vtki#127]
I am adding a conda forge package of vtki here: https://github.com/conda-forge/staged-recipes/pull/8001

Hope it's ok with you. I have also added you as a maintainer of the recipe (I can remove you if that is what you want, just let me know).

If you agree to be a maintainer you'll need to confirm it in the PR.

**Comment by hadim** [comment]
Ping @banesullivan

**Comment by akaszynski** [comment]
This is great!  Thanks!

**Comment by banesullivan** [comment]
This is awesome! Thanks, @hadim!!

I'm not seeing the maintainer invite, perhaps join us in slack? http://slack.opengeovis.org

**Comment by hadim** [comment]
There is no invitation, you just need to comment on the PR https://github.com/conda-forge/staged-recipes/pull/8001, saying you're ok to be a maintainer so the dev from the conda-forge team will see it.

@akaszynski do you also want to be a maintainer ?

**Comment by hadim** [comment]
Packages will be available very soon: https://github.com/conda-forge/vtki-feedstock

Usually, conda-forge automatically detects new PyPi releases and will make a PR at https://github.com/conda-forge/vtki-feedstock updating the vtki version. So after each new releases, wait a few hours and then check https://github.com/conda-forge/vtki-feedstock. If the PR's builds pass, then you can safely merge the PR that will upload packages to conda-forge.

**Comment by hadim** [comment]
I confirm the package works on my system (Linux, Python 3.7).

**Comment by banesullivan** [comment]
Tried creating a dummy conda env to install/test and I'm getting this error:

Mac OS X, Python 3.7

```zsh
(base) ➜ conda create -n foo python=3.7
(base) ➜ conda activate foo
(foo) ➜ conda config --add channels conda-forge
(foo) ➜ conda install vtki
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - vtki -> libgcc-ng[version='>=7.3.0']
```

**Comment by hadim** [comment]
@chrisburr: could you look at the message above this one? Do you think removing the C compiler dependency from the recipe is ok? Since we compile nothing during the build (the package is noarch), I guess we don't need a C compiler. That being said the package depends on vtk which is tied to a C compiler... What are the conda-forge recommendations here?

**Comment by banesullivan** [comment]
FYI: put this together to help test if deployments are working

https://github.com/vtkiorg/vtki-deployment-test

Travis is live - will have AppVeyor soon here as well

**Comment by banesullivan** [comment]
**Should we drop support for Python 2.7 on Anaconda?** See the latest failing builds on Travis for the [vtkiorg/vtki-deployment-test/builds](https://github.com/vtkiorg/vtki-deployment-test) repository: https://travis-ci.org/vtkiorg/vtki-deployment-test/builds

**Comment by hadim** [comment]
On Linux, vtk needs this package to avoid this bug: `mesa-libGL-devel` (this is the name for Fedora, adapt it to your distrib).

**Comment by banesullivan** [comment]
How exactly would I install this? Tried `apt-get`'ing it without any luck... but I am very unfamiliar with install Linux packages.

**Comment by hadim** [comment]
I think for Ubuntu the package is called `libgl1-mesa-dev`: `sudo apt install libgl1-mesa-dev`

About https://github.com/vtkiorg/vtki/issues/127#issuecomment-473733245, I would suggest you to open an issue on the vtki feedstock repo: https://github.com/conda-forge/vtki-feedstock.

**Comment by banesullivan** [comment]
Added the issue! Weird that I'm not getting that issue on any of the CIs....

I got `libgl1-mesa-dev` installed on the Travis build but still getting the `ImportError`

I'm just going mark the conda 2.7 install as an allowed failure. Otherwise, everything looks great on AppVeyor for Windows and all other versions of Python on Linux.

**Comment by hadim** [comment]
Looks great.
