### ISSUE TITLE
What's going on with the lighting?

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#132]
Why does the lighting seem to stay linked to a data object? Shouldn't the light source be where the camera is located and project light onto the data scene?

Can we fix the lighting to be more like ParaView's lighting?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/54655063-0adf7300-4a86-11e9-884c-8f69979cb95e.gif)

**Comment by akaszynski** [comment]
Looks like this is an ongoing topic of discussion:
https://public.kitware.com/pipermail/paraview-developers/2017-October/005612.html

Seems to me that it depends on if you prefer the lighting to remain fixed to the scene or stay attached to the camera as is default in ParaView.

I agree that our lighting could be better, and I'll look into using ``vtkLightKit`` to provide the user with the option to modify the lighting.

**Comment by akaszynski** [comment]
See PR #133
