### ISSUE TITLE
Windows exit button causes crash

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#135]
Can we fix how the pressing the exit button on the interactive renderer on Windows causes a crash? Currently, users can only use the `Q` key on Windows OS to close a rendering window.

@akaszynski - do you have a windows machine to test this on?

I can add a gif later if needed

**Comment by akaszynski** [comment]
Got a windows machine.  I’ll test it tonight.

**Comment by banesullivan** [comment]
Thanks, Alex!

**Comment by akaszynski** [comment]
Fixed in #136
