### ISSUE TITLE
should scalar bar show opacity?

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#140]
Should we display the opacity mapping on the scalar bar when plotting an array-based opacity mapping? See [the opacity example](http://docs.vtki.org/en/latest/examples/quick/plot/plot-opacity.html) below.

How would we do this? Would it be a simple fix when sending the lookup table to the scalar bar actor/mapper?

![opacity-linear](https://user-images.githubusercontent.com/22067021/54835438-b3105a00-4c87-11e9-9cd9-40a4e6fa375c.png)

**Comment by akaszynski** [comment]
It's a good idea, but we might think about adding a boundary to the scalar bar so that it's clear.  I'll have to plot if it looks better.  BTW, this example looks great!

**Comment by banesullivan** [comment]
@akaszynski: I'm not sure about the best way to draw an outline around the scalar bar... I added this new feature in 3facb47 but it doesn't look great:

```py
import vtki
from vtki import examples

vtki.set_plot_theme('doc')

m = examples.download_st_helens().warp_by_scalar()

p = vtki.Plotter()
p.add_mesh(m, opacity='linear', scalar_bar_args=dict(outline=True))
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/55647027-db28ae80-5799-11e9-84d2-022868423aea.png)
