### ISSUE TITLE
Create a downloaded example directory after install

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#142]
There are a lot of downloadable examples in `vtki` that I often use for demos and examples in the docs:

```py
import vtki
from vtki import examples
mesh = examples.download_topo_global()
mesh.compute_normals()
mesh.GetPointData().SetActiveNormals('Normals')
warp = mesh.warp_by_scalar(scale_factor=0.5e-5)
warp.plot(cmap='gist_earth', show_grid=True)
```

I'm wondering if there is a **safe** way for those example data files to get saved in the `examples` directory  under a new directory we could add to the `.gitignore` within the `vtki` package?

I could easily implement a check to see if the example dataset has been downloaded before and if not, download it - reducing download time so datasets aren't redownloaded on every call to `examples.download_*`. However, I am nervous to implement this as some users install `vtki` to their system python distributions... 

I've always used Anaconda to manage my Python envs so permissions aren't an issue but I know a lot of `vtki`'s users harness a system Python which might not give `vtki` permission to save/alter files in the `site-packages` folder because it's in some system level directory.

What do you think, @akaszynski?

**Comment by akaszynski** [comment]
It might be best not to save in the ``site-packages`` folder, but instead create a new folder in the user data directory.  The module ``appdirs`` is great for this as it's cross platform.

```python
import appdirs
vtki_path = appdirs.user_data_dir('vtki')
examples_path = os.path.join(vtki_path, 'examples')
```

On ``pip uninstall vtki`` we might run into issues where the user data isn't removed on uninstall.  I can't seem to think of an approach or a hook that removes the example directory on uninstall.

**Comment by akaszynski** [comment]
Another alternative would be to create another package ``vtki-examples`` that you could optionally download.  This would solve both issues, but the user would have to download the entire package.
