### ISSUE TITLE
Add ExodusII reader

### ISSUE THREAD

**Issue by daniellivingston** [vtkiorg/vtki#143]
It would be extraordinarily beneficial to add the ExodusII reader. This is a relatively common format used for subsurface flow and transport solvers.

[VTK api](https://vtk.org/doc/nightly/html/classvtkExodusIIReader.html) • [Python syntax](https://itk.org/Wiki/VTK/Examples/Python/ExodusII/Read) • [ExodusII specification](http://gsjaardema.github.io/seacas/exodusII-new.pdf) (PDF)

I can send sample `.exo` meshes if you wish.

**Comment by akaszynski** [comment]
A sample mesh would be great.

**Comment by daniellivingston** [comment]
Attached is a sample folder with two meshes: one with eight sidesets (`mesh_fs8.exo`) and one with three sidesets (`mesh_fs3.exo`). They can be viewed natively with ParaView.

[ExodusSampleMeshes.zip](https://github.com/vtkiorg/vtki/files/3024612/ExodusSampleMeshes.zip)

<img width="826" alt="Screen Shot 2019-03-29 at 3 30 35 PM" src="https://user-images.githubusercontent.com/20751300/55263744-b1223a00-5237-11e9-89ce-abd644533663.png">
<img width="707" alt="1" src="https://user-images.githubusercontent.com/20751300/55263745-b1bad080-5237-11e9-902c-f5ca63d0ba9b.png">

**Comment by banesullivan** [comment]
Thanks for the example mesh file and the resources! I'll get working on this ASAP

**Comment by banesullivan** [comment]
@daniellivingston: I presume you made the above two figures using ParaView? - I can easily reproduce the second figure but how did you make the first figure?

**Comment by banesullivan** [comment]
I'm working towards making a generalized Exodus reading routine utilizing VTK's ExodusII reader. This seems like an incredibly complex file format and I'm worried has a lot of nuances I'm missing. 

@daniellivingston, could you help me implement the following function which I will adapt into some new code in `vtki` to set the default parameters for reading ExodusII files?

```py
import vtki

def read_exodus(filename, 
                animate_mode_shapes=True, 
                apply_displacements=True, 
                displacement_magnitude=1.0,
                side_set=False):
    import vtk
    # Read Exodus Data
    reader = vtk.vtkExodusIIReader()
    reader.SetFileName(filename)
    reader.UpdateInformation()
    reader.SetAnimateModeShapes(animate_mode_shapes)
    reader.SetApplyDisplacements(apply_displacements)
    reader.SetDisplacementMagnitude(displacement_magnitude)
    #??? how? reader.SetSideSetArrayStatus(vtk.vtkExodusIIReader.SIDE_SET, side_set)
    reader.Update()
    return vtki.wrap(reader.GetOutput())

blocks = read_exodus('mesh_fs3.exo')
```


Then you can access the unerlying VTK data tree:

```py
>>> blocks.n_blocks
8
>>> blocks.keys()
['Element Blocks',
 'Face Blocks',
 'Edge Blocks',
 'Element Sets',
 'Side Sets',
 'Face Sets',
 'Edge Sets',
 'Node Sets']
```

```py
meshes = blocks['Element Blocks']
meshes.plot()
```

![download](https://user-images.githubusercontent.com/22067021/55292578-d9ca4100-53a9-11e9-98ae-3bde84792f8c.png)

**Comment by daniellivingston** [comment]
@banesullivan , awesome, awesome work, thank you so much.

So broadly, sidesets are discrete sections of a mesh's surface. Their topology is, I believe, exclusively 2D. The main use-case for sidesets is to set certain boundary conditions for multiphysics solvers. They may be exclusive, wherein no two sidesets of a mesh spatially overlap, or inclusive, where they do. Generally exclusive, at least in all of the cases I've seen.

Regarding the generated figures, you can display them in ParaView under *Properties -> Sets*.

![Apr-01-2019 11-01-39](https://user-images.githubusercontent.com/20751300/55345706-d26c6b80-546d-11e9-85af-c98c34e6922c.gif)

By default, VTK sets the side set array status to 0. Turning them on can be done by:

        for ss_id in range(reader.GetNumberOfSideSetArrays()):
            reader.SetSideSetArrayStatus(reader.GetSideSetArrayName(ss_id),1)

**Comment by daniellivingston** [comment]
I would recommend something like:

```python
def read_exodus(filename:str, 
                animate_mode_shapes:bool=True, 
                apply_displacements:bool=True, 
                displacement_magnitude:float=1.0,
                enabled_sidesets:list=None) -> vtki.container.MultiBlock:
    import vtk
    # Read Exodus Data
    reader = vtk.vtkExodusIIReader()
    reader.SetFileName(filename)
    reader.UpdateInformation()
    reader.SetAnimateModeShapes(animate_mode_shapes)
    reader.SetApplyDisplacements(apply_displacements)
    reader.SetDisplacementMagnitude(displacement_magnitude)

    if enabled_sidesets is None:
        enabled_sidesets = list(range(reader.GetNumberOfSideSetArrays()))

    for sideset in enabled_sidesets:
        if isinstance(sideset,int):
            name = reader.GetSideSetArrayName(sideset)
        elif isinstance(sideset,str):
            name = sideset
        else:
            raise ValueError('Could not parse sideset ID/name: {}'\
                .format(sideset))

        reader.SetSideSetArrayStatus(name,1)

    reader.Update()
    return vtki.wrap(reader.GetOutput())
```

Then, sidesets can be selectively enabled:

```python
blocks = read_exodus('mesh_fs8.exo') # Enable all sidesets
blocks = read_exodus('mesh_fs8.exo',enabled_sidesets=[0,1,3]) # Enable by index
blocks = read_exodus('mesh_fs8.exo',enabled_sidesets=['Unnamed set ID: 3','Unnamed set ID: 7']) # Enable by name
```

<img width="512" alt="sss2" src="https://user-images.githubusercontent.com/20751300/55346932-db127100-5470-11e9-8300-820429f7a2fa.png">

<img width="512" alt="ss1" src="https://user-images.githubusercontent.com/20751300/55346933-dbab0780-5470-11e9-859a-747ad0aaf520.png">

Conversely, I wouldn't be opposed to just ignoring the selective enabling and just enabling all sidesets on read.

**Comment by banesullivan** [comment]
This is awesome! Thanks, @daniellivingston!

Now I'm brainstorming how to implement this in `vtki`... I'm thinking of just adding that exact function to `vtki` and setting the `vtki.read` function to call `vtki.read_exodus` when `'.exo'` file extensions are given. What do you think about that? 

- Is this function general enough to handle most Exodus files?
- Are there other extensions commonly used for this same file format?

**Comment by daniellivingston** [comment]
Sounds good to me!

* I believe there are only two valid extensions, `.e.` and `.exo` (see  [this document](https://publications.anl.gov/anlpubs/2014/12/79486.pdf) (PDF):  *"The program requires input in the form of one or more EXODUS II finite element meshes with proper extension type (“.e” or “.exo”)."*)

* I've tried a few other meshes with this, and they all work great. I could try to come up with some edge cases using [pyexodus](https://salvushub.github.io/pyexodus/) or this ([1](http://gsjaardema.github.io/seacas/exodus.html#exodus), [2](https://github.com/gsjaardema/seacas/blob/master/packages/seacas/scripts/exodus.py.in)). But I think we're in a pretty good place.
