### ISSUE TITLE
default error output

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#151]
A while back, I added the function `vtki.set_error_output_file` which allows users to capture the VTK error/warning output window to a file. I've noticed recently while helping windows folks use `vtki` that VTK warnings pop out into a separate window (this doesn't happen on my mac - it stays on the command line output). 

I'm thinking that most users don't need or want to see that separate error/warning output window. This leads me to think that maybe we should set a default temp file for writing the error messages?

Perhaps we could write to an active object in `vtki` which could parse the VTK errors/warnings for useful information to warn the user through the `logging` module?

**Comment by akaszynski** [comment]
This would be really helpful.  It's funny how Linux/Mac OS behave differently than Windows for internal VTK errors.  I think having all the output redirected to a logger would be best perhaps at the "WARNING" level as these errors sometimes don't stop execution.  "ERROR" would be fine too.

**Comment by banesullivan** [comment]
>  I think having all the output redirected to a logger would be best perhaps at the "WARNING" level as these errors sometimes don't stop execution

I can go ahead and implement this - and close #153. #153 can't merge as it would be problematic if imported somewhere where the error messages matter like in ParaView (PVGeo uses `vtki` directly in ParaView).

>  "ERROR" would be fine too.

I can try to write a catch for these and pass them to the logger but they most likely will just cause a segfault and crash the thread.
