### ISSUE TITLE
issue matplolib backend with sphinx gallery

### ISSUE THREAD

**Issue by agramfort** [vtkiorg/vtki#166]
trying to import vtki from an interactive ipython session with --matplotlib option I get an error.

```
ValueError: Sphinx-Gallery relies on the matplotlib 'agg' backend to render figures and write them to files. You are currently using the Qt5Agg backend. Sphinx-Gallery will terminate the build now, because changing backends is not well supported by matplotlib. We advise you to move sphinx_gallery imports before any matplotlib-dependent import. Moving sphinx_gallery imports at the top of your conf.py file should fix this issue
```

None of the project that use sphinx-gallery for the doc import it in their source tree. The dependency to sphinx-gallery should be limited to its doc or at least the sphinx-gallery import should be protected with a nested import.

FYI we are considering with @GuillaumeFavelier and @larsoner to use vtki for this project http://martinos.org/mne/stable/index.html that so far relies on mayavi.

**Comment by banesullivan** [comment]
Thanks for pointing this out, @agramfort! I was also experiencing the `matplotlib` backend issue but didn't realize the `shinx_gallery` import was causing the issue.

Please see changes in 1a485d3 - these should fix the issue

I'll push a patch release when you close this issue

**Comment by agramfort** [comment]
works. Thanks for the quick fix

**Comment by banesullivan** [comment]
`v0.18.2` is on its way!

**Comment by agramfort** [comment]
great !

>

**Comment by banesullivan** [comment]
Also: 👋 @agramfort, @GuillaumeFavelier, and @larsoner!

MNE looks like an awesome project! Thanks for poking around `vtki` to see if it would be a good fit/replacement for mayavi. I've been seeking out projects in need of 3D viz lately and would be happy to collaborate with you all on getting `vtki` support within MNE to showcase how `vtki` can be used as a supporting module for 3D viz

**Comment by larsoner** [comment]
@GuillaumeFavelier has already been working on a 3D viz abstraction layer for MNE (mayavi/vtki/VisPy), and vtki support is in progress in https://github.com/mne-tools/mne-python/pull/6153. Hopefully it's straightforward!
