### ISSUE TITLE
[Travis]: fix 3.7/docs build for external PRs

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#169]
External PRs will fail on Travis due to the way the docs are deployed. We should add some sort of hook that only deploys the docs from the `vtki` master branch (not other people's forked master branches)

**Comment by akaszynski** [comment]
You have access as admin, right?  Or do you need me to fix this?

**Comment by banesullivan** [comment]
I have admin access and can fix it just not sure what needs to be done at the moment

**Comment by akaszynski** [comment]
Fixed in 4d5a9a8c5693255a353b2408bdca06a5dd7156cd

**Comment by banesullivan** [comment]
Note that I changed:

https://github.com/vtkiorg/vtki/blob/919f096e2d9ce1b527abe42434ebab815dd14dc5/.travis.yml#L82

to have and conditions `&&` because we only want to deploy the docs if all three of those conditions are met

**Comment by akaszynski** [comment]
Ah, that's right.  Still not that familiar with bash I'm afraid.

**Comment by banesullivan** [comment]
Down the road when the docs are more complete and the API is more stable, we should likely change this to only update the docs on tagged releases

**Comment by akaszynski** [comment]
Agreed.

**Comment by akaszynski** [comment]
Looks like this is still an issue.  I thought it would have been solved by my commit.  Guess not.

**Comment by banesullivan** [comment]
This is a bigger headache than I could have ever imagined

**Comment by banesullivan** [comment]
Okay... like 20 commits of debugging later, I decided to just make an environmental variable that *should* only be accessible within our repo. If that variable is set correctly, then the docs will deploy.

see ecbe734

Eventually we should set it up in a deploy script but the output from deploy scripts are not shown so they are ridiculously difficult to debug

**Comment by banesullivan** [comment]
We should wait until the next external PR to close this

**Comment by banesullivan** [comment]
#178 shows this is working! Hack of a solution but it'll do for now.
