### ISSUE TITLE
What's the proper way to open parallel VTK files (*.pvtu)?

### ISSUE THREAD

**Issue by JiaweiZhuang** [vtkiorg/vtki#175]
First thanks for this wonderful package! It is a much more sane way to manipulate VTK files in Python...

I wonder what's the proper way to open [parallel VTK files](https://www.paraview.org/ParaView/index.php/Parallel_I/O)? It consists of a header file (`*.pvtu`) that points to normal VTK files (`*.vtu`). In ParaView, you can simply open the top-level `*.pvtu` file, and ParaView will automatically assemble the small VTK files into a single object.

Directly calling `vtki.read('*.pvtu')` leads to `OSError: This file was not able to be automatically read by vtki.`. So I open each small VTU file and use `vtki.pointset.UnstructuredGrid.merge()` to put them together.  The full reproducible code is at https://github.com/JiaweiZhuang/vtk_experiments/blob/master/vtki_read_pvtu.ipynb, with small sample data files.

However, `merge()` seems to have problems at the boundaries between different subdomains:

![pvtu_plot_density](https://user-images.githubusercontent.com/25473287/56383411-b98ee480-61e7-11e9-9b1b-9c47dda37dfd.png)

The blue/green lines are artifacts that shouldn't exist in the original data. They correspond to the boundaries of domain-decomposition: 

![pvtu_plot_node](https://user-images.githubusercontent.com/25473287/56383395-b3990380-61e7-11e9-82cd-91c9d861f056.png)

Here each color represents a VTK file.

Thus I wonder that's the proper way to open and merge parallel VTK files? Would it be useful to add an API similar to [Xarray](http://xarray.pydata.org)'s [`open_mfdataset()`](http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html) to deal with multiple files?

Disclaimer: I have zero experience with VTK, but need to process some VTK files for a class project. Please forgive me if I miss anything obvious  :)

**Comment by JiaweiZhuang** [comment]
OK it seems that ParaView gives exactly the same artifact... So that's probably an issue with my data!

Anyway I still think that a stream-lined `vtki.read('*.pvtu')` utility could be useful :)

<img width="653" alt="Screen Shot 2019-04-18 at 2 53 58 PM" src="https://user-images.githubusercontent.com/25473287/56384195-d5938580-61e9-11e9-9f6f-27fd12843b44.png">

**Comment by banesullivan** [comment]
Hi @JiaweiZhuang! Thanks for your feedback and I'm glad you're enjoying `vtki`!

A great example by the way - would it be okay to use those data files you shared for an example in the `vtki` docs on how to do this?

> OK it seems that ParaView gives exactly the same artifact... So that's probably an issue with my data!

Those artifacts are indeed weird... I'll look into a way to fix this. In the meantime:

> Anyway I still think that a stream-lined vtki.read('*.pvtu') utility could be useful :)

I'll focus on adding a reader for parallel files for this issue

**Comment by banesullivan** [comment]
Note these features are now implemented in the master branch!
```py
ds = vtki.read('./data_pvtu/T0000000500.pvtu')  # this works now!
ds
```

**Comment by JiaweiZhuang** [comment]
Great, thanks for such a fast response! 

> would it be okay to use those data files you shared for an example in the `vtki` docs on how to do this?

Let me ask my class instructor...

**Comment by JiaweiZhuang** [comment]
OK the instructor says that it is OK to share the files.

I have uploaded the correct files (without boundary artifacts) at https://github.com/JiaweiZhuang/vtk_experiments/tree/master/data_pvtu_corrected

Code to plot the files is at:
https://github.com/JiaweiZhuang/vtk_experiments/blob/master/vtki_correct_pvtu.ipynb

The data represent the [bifurcation of blood vessels](https://medical-dictionary.thefreedictionary.com/bifurcation).

**Comment by banesullivan** [comment]
Awesome, thanks @JiaweiZhuang! Would it be okay for me to move those data files into a folder under https://github.com/vtkiorg/vtk-data so that we can implement an example for it:

```py
from vtki import examples
vessels = examples.download_blood_vessels()
```

**Comment by JiaweiZhuang** [comment]
Yes I think that's okay!

**Comment by banesullivan** [comment]
It's now on the master branch and an example is live in docs: http://docs.vtki.org/examples/00-load/read-parallel.html
