### ISSUE TITLE
headless displays on remote server with port-forwarding

### ISSUE THREAD

**Issue by JiaweiZhuang** [vtkiorg/vtki#177]
How to properly use vtki on remote servers?

On a remote server with [port-forwarding](https://medium.com/@alexjsanchez/python-3-notebooks-on-aws-ec2-in-15-mostly-easy-steps-2ec5e662c6c6) (i.e. `ssh  ... -L 8888:localhost:8888`), the Jupyter kernel always dies when I call `plot()` on vtki objects (`The kernel appears to have died. It will restart automatically.`) . This happens on both AWS EC2 and a local cluster.

A minimum reproducible code is:
```python
import vtki
from vtki import examples
ds = examples.load_airplane() 

ds.plot(use_pane=True)  # this kills the kernel
# use_panel=False gives the same error
```

Similar in `ipython`:

```
In [1]: import vtki
   ...: from vtki import examples
   ...: ds = examples.load_airplane()

In [2]: ds.plot()
ERROR:root:bad X server connection. DISPLAY=
Aborted (core dumped)
```

In principle it should work on remote servers, because the Binder demos are working properly. But Binder is connected directly via HTTP, while on most remote servers people would use SSH+port-forwarding.

## Environment setup

I am using EC2 Ubuntu 18.04 LTS (`ami-0a313d6098716f372` in `us-east-1`). The complete steps to install the packages are:

```bash
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p miniconda
echo '. $HOME/miniconda/etc/profile.d/conda.sh' >> ~/.bashrc && source ~/.bashrc
conda create --name vtk python=3.7
conda activate vtk
conda install nodejs  # required when importing vtki in Jupyter
pip install jupyter vtki panel

# To avoid "ModuleNotFoundError: No module named 'vtkOpenGLKitPython' " when importing vtk
# https://stackoverflow.com/q/32389599
# https://askubuntu.com/q/629692
sudo apt update && sudo apt install python-qt4 libgl1-mesa-glx

python -c "import vtki" # it should work
```

The notebook is started with:

```bash
ssh ... -L 8888:localhost:8888
conda activate vtk
jupyter notebook --NotebookApp.token='' --no-browser --port=8888
```

**Comment by banesullivan** [comment]
This is similar to #155 where you have to set up a headless display.

After your:
```sh
sudo apt update && sudo apt install python-qt4 libgl1-mesa-glx
```

try adding the following:

```sh
sudo apt-get xvfb;
export DISPLAY=:99.0;
export VTKI_OFF_SCREEN=True;
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &;
sleep 3; # give xvfb some time to start
```

If this works for you, please consider opening a PR to update [this documentation page](http://docs.vtki.org/getting-started/installation.html#running-on-ci-services) with a section on your use case

Also note that anytime the server is launched, that snippet will have to be executed to boot up the headless display

**Comment by banesullivan** [comment]
Also, I'm not a linux person so `sudo apt-get ...` might not be correct

**Comment by JiaweiZhuang** [comment]
Works like a charm. The install should be `sudo apt-get install xvfb`. 

Just opened a PR #178. Better test on EC2 on your own to make sure it works.

**Comment by banesullivan** [comment]
> Better test on EC2 on your own to make sure it works.

What's EC2?

**Comment by JiaweiZhuang** [comment]
> What's EC2?

I mean Amazon's cloud computing service https://aws.amazon.com/ec2/. (I thought all cool kids are doing cloud nowadays!). You may follow https://aws.amazon.com/getting-started/tutorials/launch-a-virtual-machine for a quick start.

**Comment by banesullivan** [comment]
Ah, cool! We may have a number of users that would like that. Thanks for sharing!

**Comment by JiaweiZhuang** [comment]
No problem! Being a grad student who also does a bunch of geoscience and software development, I'd love to see this sort of software projects taking off.

Not sure how relevant it is, but you might also want to take a look at Xarray (http://xarray.pydata.org) and Pangeo (https://pangeo.io/) that are widely used in cloud environments. There are some important similarities between Xarray and VTK/VTKI -- both represent multi-dimensional gridded data; both are used for geoscience but also for other fields, etc. The two packages might be able to learn from each other. For example:
-  The Pangeo community are somewhat struggling with the data model for unstructured grids (pangeo-data/pangeo#356). VTK seems to have very powerful unstructured-grid-related APIs (plotting, slicing, subsetting) that we can learn from (I am speaking of the Xarray community here). 
- On the other hand, I think Xarray has the right data model for multi-variable datasets (the `Dataset` vs `DataArray` abstraction). For `vtki`, a non-ideal feature to me is that switching between variables in a `vtk.vtkDataSet` requires a somewhat implicit `set_active_scalar()` call. Following Xarray's data model, a `dataset['variable_name']` call will extra a single variable while keeping the metadata (e.g. grid coordinates that can be used for plotting). In `vtki`, `dataset['variable_name']` gives a pure numpy array without metadata. If it can instead track grid coordinates, then plotting a variable will be as simple as `dataset['variable_name'].plot()`, like in Xarray.

**Comment by adizhol** [comment]
> ```shell
> sudo apt-get install xvfb;
> export DISPLAY=:99.0;
> export VTKI_OFF_SCREEN=True;
> Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &;
> sleep 3; # give xvfb some time to start
> ```
> 
like in https://github.com/pyvista/pyvista/issues/465, it doesn't work and I get the following error:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  52
  Current serial number in output stream:  53

```

**Comment by akaszynski** [comment]
@adizhol, could you try the following?

```
xvfb-run python -c "import pyvista; pyvista.Sphere().plot(off_screen=True, screenshot='/tmp/tmp.png')"
```
You should see a screenshot generated at `'tmp/tmp.png'`.

`xvfb-run` is a convenience function that simplifies setting up `xvfb`.  Whenever I've had problems running `xvfb`, this helps out.

**Comment by adizhol** [comment]
@akaszynski 
I got `xvfb-run: error: Xvfb failed to start`

**Comment by akaszynski** [comment]
This sounds like a graphics driver issue.  Can you run anything from xvfb that requires off-screen rendering.
