### ISSUE TITLE
StreamTracer and LagrangianParticleTracker plot?

### ISSUE THREAD

**Issue by JiaweiZhuang** [vtkiorg/vtki#198]
Does vtki support [StreamTracer](https://vtk.org/doc/nightly/html/classvtkStreamTracer.html) and [LagrangianParticleTracker](https://vtk.org/doc/nightly/html/classvtkLagrangianParticleTracker.html) in VTK? See this [VTK and ParaView Add Highly Configurable Particle Tracker](https://blog.kitware.com/vtk-and-paraview-add-highly-configurable-particle-tracker/) post.

I don't seem to find any "tracer" related filters at http://docs.vtki.org/tools/filters.html. The closest one I find is [Glyphs](http://docs.vtki.org/examples/02-plot/plot-glyphs.html), but streamlines are more often used for fluids.

This can be easily done in ParaView. With the data files used in #175, the steps are
- Use ParaView to open the VTK files used in your [parallel file example](http://docs.vtki.org/examples/00-load/read-parallel.html) added by https://github.com/vtkiorg/vtki/commit/259558d9bcd07af7fd7304720e348386a14b0568
- Select the `velocity` field.
- Apply the `Stream Tracer` filter (in "Filters" - "Common")
- Set `Seed Type` to `Point Source`, increase the source region radius, increase the number of source points. My configuration is like:

<img width="300" alt="Screen Shot 2019-04-25 at 2 54 32 PM" src="https://user-images.githubusercontent.com/25473287/56761078-878efc80-676a-11e9-9ec2-b81f25a8cfc3.png">

Then you get these nice 3D streamlines:

<img width="732" alt="Screen Shot 2019-04-25 at 2 41 05 PM" src="https://user-images.githubusercontent.com/25473287/56760670-b5277600-6769-11e9-88fe-0fd79eba580b.png">

**Comment by banesullivan** [comment]
Currently, this is not implemented but we could totally add a new filtering method under `vtki.DataSetFilters` called `.stream_tracer(**kwargs)` with keyword arguments to control all the parameters for that filter. Then test and put an example in the docs using the blood vessel data!

**Comment by JiaweiZhuang** [comment]
That would be cool!

**Comment by banesullivan** [comment]
Note that down the road, we could implement a widget to control the seed source much like what's available in ParaView (that feature is definitely not low hanging fruit)

In the meantime, I think it is fair to have a user simply pass a sphere or line to the filter much like how there is the option to pass a `geom` object to the `.glyph()` filter

**Comment by JiaweiZhuang** [comment]
Yes a keyword argument for the sphere center & radius should be good enough.
