### ISSUE TITLE
Dynamically update scalar bars if data range changes

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#85]
When updating a scalar array, the scalar bar is not updated if the data range is updated. For example:

This example is from #75 
```py
from threading import Thread
import time
import numpy as np
import vtk
import vtki

sphere = vtki.Sphere()
sphere.point_arrays['scalars'] = sphere.points[:, 2]

# points = vtki_ndarray(sphere.points, sphere)

cpos = [(-1.3410801252605407, -2.735564325598376, 1.3608119983788354),
        (0.0, 0.0, 0.0),
        (0.16724779351273428, 0.37216861144284896, 0.9129724531560762)]

plotter = vtki.BackgroundPlotter()
plotter.add_mesh(sphere, lighting=False, show_edges=True, scalars='scalars')
plotter.camera_position = cpos

# shrink sphere in the background
def shrink():
    for i in range(10):
        sphere.points *= 0.9
        # Update sclars
        sphere.point_arrays['scalars'] += np.random.rand(sphere.n_points)
        time.sleep(0.5)

thread = Thread(target=shrink)
thread.start()
```

### Feature Proposal

We should add a way that the scalar bars can be updated automatically if their corresponding meshes' data ranges change.

We will likely need a way to disable this if the user wants to explicitly define the scalar range

### Questions

To implement this, we'll need some sort of callback or observer that will fetch the data ranges for each array linked to a scalar bar. This could turn into quite a bit of overhead if we do this on every render call.... perhaps there is a way to link the VTK scalar bar to the Cell/Point data to listen for a `Modified()` call?

**Comment by banesullivan** [comment]
Possibly integrate with efforts on #79

**Comment by akaszynski** [comment]
This can be done by using the same approach in #75 with relatively small overhead as ``np.min`` and ``np.max`` (or ``np.nanmin`` and ``np.nanmax``) execute quickly.  However, this adding a conditional function to the ``vtki_ndarray`` or creating a separate class that handles this.

Considering that it's not always helpful to update the scalar bar (especially when plotting value vs time responses), maybe we can just make it easier to change existing scalar bars or update scalar bar ranges?

For example, all we really need to call is
```python
plotter.mapper.SetScalarRange(data.min(), data.max())
```

Maybe we can implement a ``reset_ranges`` or ``update_ranges`` method in the ``BasePlotter`` class?

**Comment by banesullivan** [comment]
Now use the `update_scalar_bar_range` method for this functionality
